# Generated by Django 6.0.3 on 2026-04-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_pedido_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
